$(function(){
	$("#add_notebook").click(function(){
		$("#can").load("alert/alert_notebook.html",function(){
				$(".close").click(function(){
					$("#can").hide();
				});
		});
		$("#can").show();
	});
})